from __future__ import annotations

APP_NAME = "EasyDL"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8001
DEFAULT_UPDATE_MAX_PAGES = 2
DEFAULT_UPDATE_TTL_HOURS = 24
FUCKINGFAST_HOSTS = {"fuckingfast.co", "www.fuckingfast.co"}
PROGRESS_DB_WRITE_INTERVAL_SECONDS = 5
START_RESOLVE_CONCURRENCY = 4
